version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend/frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - API_URL=http://backend:8000

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
